// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: api/proto/v1/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignupStatus int32

const (
	SignupStatus_SIGNUP_STATUS_UNSPECIFIED SignupStatus = 0
	SignupStatus_OTP_SENT                  SignupStatus = 1
	SignupStatus_RATE_LIMITED              SignupStatus = 2
	SignupStatus_INVALID_PHONE             SignupStatus = 3
	SignupStatus_INTERNAL_ERROR            SignupStatus = 4
)

// Enum value maps for SignupStatus.
var (
	SignupStatus_name = map[int32]string{
		0: "SIGNUP_STATUS_UNSPECIFIED",
		1: "OTP_SENT",
		2: "RATE_LIMITED",
		3: "INVALID_PHONE",
		4: "INTERNAL_ERROR",
	}
	SignupStatus_value = map[string]int32{
		"SIGNUP_STATUS_UNSPECIFIED": 0,
		"OTP_SENT":                  1,
		"RATE_LIMITED":              2,
		"INVALID_PHONE":             3,
		"INTERNAL_ERROR":            4,
	}
)

func (x SignupStatus) Enum() *SignupStatus {
	p := new(SignupStatus)
	*p = x
	return p
}

func (x SignupStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignupStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_auth_proto_enumTypes[0].Descriptor()
}

func (SignupStatus) Type() protoreflect.EnumType {
	return &file_api_proto_v1_auth_proto_enumTypes[0]
}

func (x SignupStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignupStatus.Descriptor instead.
func (SignupStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_auth_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	AuthProvider  string                 `protobuf:"bytes,5,opt,name=auth_provider,json=authProvider,proto3" json:"auth_provider,omitempty"` // "local", "google", "github"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_proto_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *User) GetAuthProvider() string {
	if x != nil {
		return x.AuthProvider
	}
	return ""
}

type AuthTokens struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	SessionId        string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccessExpiresAt  int64                  `protobuf:"varint,4,opt,name=access_expires_at,json=accessExpiresAt,proto3" json:"access_expires_at,omitempty"`
	RefreshExpiresAt int64                  `protobuf:"varint,5,opt,name=refresh_expires_at,json=refreshExpiresAt,proto3" json:"refresh_expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthTokens) Reset() {
	*x = AuthTokens{}
	mi := &file_api_proto_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokens) ProtoMessage() {}

func (x *AuthTokens) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokens.ProtoReflect.Descriptor instead.
func (*AuthTokens) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthTokens) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthTokens) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AuthTokens) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthTokens) GetAccessExpiresAt() int64 {
	if x != nil {
		return x.AccessExpiresAt
	}
	return 0
}

func (x *AuthTokens) GetRefreshExpiresAt() int64 {
	if x != nil {
		return x.RefreshExpiresAt
	}
	return 0
}

type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Firstname     string                 `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_api_proto_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpRequest) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *SignUpRequest) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignUpResponce struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SignupSessionId string                 `protobuf:"bytes,1,opt,name=signup_session_id,json=signupSessionId,proto3" json:"signup_session_id,omitempty"`
	Status          SignupStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=mergespace.v1.SignupStatus" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignUpResponce) Reset() {
	*x = SignUpResponce{}
	mi := &file_api_proto_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponce) ProtoMessage() {}

func (x *SignUpResponce) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponce.ProtoReflect.Descriptor instead.
func (*SignUpResponce) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SignUpResponce) GetSignupSessionId() string {
	if x != nil {
		return x.SignupSessionId
	}
	return ""
}

func (x *SignUpResponce) GetStatus() SignupStatus {
	if x != nil {
		return x.Status
	}
	return SignupStatus_SIGNUP_STATUS_UNSPECIFIED
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Tokens        *AuthTokens            `protobuf:"bytes,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_api_proto_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *AuthResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthResponse) GetTokens() *AuthTokens {
	if x != nil {
		return x.Tokens
	}
	return nil
}

var File_api_proto_v1_auth_proto protoreflect.FileDescriptor

const file_api_proto_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/v1/auth.proto\x12\rmergespace.v1\"\x85\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rauth_provider\x18\x05 \x01(\tR\fauthProvider\"\xcd\x01\n" +
	"\n" +
	"AuthTokens\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12*\n" +
	"\x11access_expires_at\x18\x04 \x01(\x03R\x0faccessExpiresAt\x12,\n" +
	"\x12refresh_expires_at\x18\x05 \x01(\x03R\x10refreshExpiresAt\"{\n" +
	"\rSignUpRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1c\n" +
	"\tfirstname\x18\x02 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x03 \x01(\tR\blastname\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"q\n" +
	"\x0eSignUpResponce\x12*\n" +
	"\x11signup_session_id\x18\x01 \x01(\tR\x0fsignupSessionId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.mergespace.v1.SignupStatusR\x06status\"j\n" +
	"\fAuthResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.mergespace.v1.UserR\x04user\x121\n" +
	"\x06tokens\x18\x02 \x01(\v2\x19.mergespace.v1.AuthTokensR\x06tokens*t\n" +
	"\fSignupStatus\x12\x1d\n" +
	"\x19SIGNUP_STATUS_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bOTP_SENT\x10\x01\x12\x10\n" +
	"\fRATE_LIMITED\x10\x02\x12\x11\n" +
	"\rINVALID_PHONE\x10\x03\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x042\\\n" +
	"\vAuthService\x12M\n" +
	"\x0eInitiateSignup\x12\x1c.mergespace.v1.SignUpRequest\x1a\x1d.mergespace.v1.SignUpResponceB\x15Z\x13api/proto/v1;authpbb\x06proto3"

var (
	file_api_proto_v1_auth_proto_rawDescOnce sync.Once
	file_api_proto_v1_auth_proto_rawDescData []byte
)

func file_api_proto_v1_auth_proto_rawDescGZIP() []byte {
	file_api_proto_v1_auth_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_auth_proto_rawDesc), len(file_api_proto_v1_auth_proto_rawDesc)))
	})
	return file_api_proto_v1_auth_proto_rawDescData
}

var file_api_proto_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_v1_auth_proto_goTypes = []any{
	(SignupStatus)(0),      // 0: mergespace.v1.SignupStatus
	(*User)(nil),           // 1: mergespace.v1.User
	(*AuthTokens)(nil),     // 2: mergespace.v1.AuthTokens
	(*SignUpRequest)(nil),  // 3: mergespace.v1.SignUpRequest
	(*SignUpResponce)(nil), // 4: mergespace.v1.SignUpResponce
	(*AuthResponse)(nil),   // 5: mergespace.v1.AuthResponse
}
var file_api_proto_v1_auth_proto_depIdxs = []int32{
	0, // 0: mergespace.v1.SignUpResponce.status:type_name -> mergespace.v1.SignupStatus
	1, // 1: mergespace.v1.AuthResponse.user:type_name -> mergespace.v1.User
	2, // 2: mergespace.v1.AuthResponse.tokens:type_name -> mergespace.v1.AuthTokens
	3, // 3: mergespace.v1.AuthService.InitiateSignup:input_type -> mergespace.v1.SignUpRequest
	4, // 4: mergespace.v1.AuthService.InitiateSignup:output_type -> mergespace.v1.SignUpResponce
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_v1_auth_proto_init() }
func file_api_proto_v1_auth_proto_init() {
	if File_api_proto_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_auth_proto_rawDesc), len(file_api_proto_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_auth_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_auth_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_auth_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_auth_proto_msgTypes,
	}.Build()
	File_api_proto_v1_auth_proto = out.File
	file_api_proto_v1_auth_proto_goTypes = nil
	file_api_proto_v1_auth_proto_depIdxs = nil
}
